server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/questionnaire?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.aim.questionnaire.dao.entity
  mapperLocations: classpath:mapper/*.xml
  #开启MyBatis的二级缓存
  configuration:
    cache-enabled: true